<?php

namespace AppBundle\Repository;

/**
 * BigEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BigEventRepository extends \Doctrine\ORM\EntityRepository
{
}
